### ISSUE TITLE
Add default version of software installed to the $PATH

### ISSUE THREAD

**Issue by bschwedler** [rstudio/rstudio-docker-products#867]
Given that we are installing a specific version of software like Python and R, we should expect that these executables be available in users' PATH by default.

```[tasklist]
### Tasks
- [ ] Add default Python executables to `$PATH`
- [ ] Add default R executables to `$PATH`
- [ ] Add default Quarto executables to `$PATH`
- [ ] Examine other software that we install that we want to add to the 
```
